### ISSUE TITLE
URGENT!REMOTE ACCESS TROJAN

### ISSUE THREAD

**Issue by cheeziest** [threevt/3arthh4ck#3]
I have reason to believe this jar file (3arthh4ck) contains malicious code similar to that of a RAT (Remote Access Trojan), a malicious program that, unbeknownst to the user, opens a back door in the users computer, allowing the perpetrator/s full full access to the user’s PC (Personal Computer.) I will be contacting the appropriate authorities and you will be punished greatly for this despicable crime.

**Comment by master7720** [comment]
um
